# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=40)),
                ('QQ', models.CharField(max_length=12)),
            ],
        ),
    ]
